//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AuditEventsFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuditEventsFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecurityManager.AuditEventsFile", typeof(AuditEventsFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik {0} nije prošao autentifikaciju..
        /// </summary>
        internal static string NeuspesnaAutentifikacija {
            get {
                return ResourceManager.GetString("NeuspesnaAutentifikacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik {0} nije autorizovan za operaciju: {1}.
        /// </summary>
        internal static string NeuspesnaAutorizacija {
            get {
                return ResourceManager.GetString("NeuspesnaAutorizacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik {0} nije izmenio koncert za id: {1} Naziv: {2} | Razlog: {3}.
        /// </summary>
        internal static string NeuspesnaIzmena {
            get {
                return ResourceManager.GetString("NeuspesnaIzmena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik {0} nije uspeo da rezerviše karte za koncert {1} | Razlog: {2}.
        /// </summary>
        internal static string NeuspesnaRezervacija {
            get {
                return ResourceManager.GetString("NeuspesnaRezervacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik {0} nije dodao koncert za id: {1} Naziv: {2} | Razlog: {3}.
        /// </summary>
        internal static string NeuspesnoDodavanje {
            get {
                return ResourceManager.GetString("NeuspesnoDodavanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik {0} nije uspeo da plati karte ({1}) za koncert {2} | Razlog: {3}.
        /// </summary>
        internal static string NeuspesnoPlacanje {
            get {
                return ResourceManager.GetString("NeuspesnoPlacanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik {0} se uspešno autentifikovao..
        /// </summary>
        internal static string UspesnaAutentifikacija {
            get {
                return ResourceManager.GetString("UspesnaAutentifikacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik {0} je uspešno izmenio koncert za id: {1} Naziv: {2}.
        /// </summary>
        internal static string UspesnaIzmena {
            get {
                return ResourceManager.GetString("UspesnaIzmena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik {0} je uspešno rezervisao karte ({1}) za koncert {2}..
        /// </summary>
        internal static string UspesnaRezervacija {
            get {
                return ResourceManager.GetString("UspesnaRezervacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik {0} je uspešno dodao koncert za id: {1} Naziv: {2}.
        /// </summary>
        internal static string UspesnoDodavanje {
            get {
                return ResourceManager.GetString("UspesnoDodavanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik {0} je uspešno platio karte ({1}) za koncert {2} u iznosu od: {3}.
        /// </summary>
        internal static string UspesnoPlacanje {
            get {
                return ResourceManager.GetString("UspesnoPlacanje", resourceCulture);
            }
        }
    }
}
